import {auth,db,connect,message} from '../web-account.js';
import '../help-link.js';
import {collection,query,where,limit,getDocs,getDoc,doc,onSnapshot} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';
let stop=null,records=[],count=50,admin=false,generation=0;
const $=s=>document.querySelector(s);
const labels={submitted:'Awaiting review',information_cleared:'Information cleared',needs_changes:'Changes requested',rejected:'Rejected',not_verified:'Not verified',verified:'Verified',not_eligible:'Not eligible',approved_for_external_payment:'Approved for external payment',paid_externally:'Recorded paid externally',monthly:'Monthly',six_months:'Six months',annual:'Annual',undecided:'Undecided'};
const label=x=>labels[x]||String(x||'Not recorded').replaceAll('_',' ');
function clear(){stop?.();stop=null;records=[];$('#records').replaceChildren();$('#summary').textContent='';$('#dashboard').hidden=true;}
function render(){
 const search=$('#search').value.trim().toLowerCase(),filter=$('#filter').value;
 const visible=records.filter(r=>[r.businessName,r.customerName,r.referralCode,admin?r.salesAgentName:''].join(' ').toLowerCase().includes(search)).filter(r=>filter==='all'||(filter==='pending'?r.paymentVerificationStatus!=='verified':filter==='verified'?r.paymentVerificationStatus==='verified':r.commissionStatus===filter));
 $('#summary').textContent=`${records.length} loaded · ${records.filter(r=>r.paymentVerificationStatus==='verified').length} verified purchases · ${records.filter(r=>r.commissionStatus==='approved_for_external_payment').length} commissions approved · ${records.filter(r=>r.commissionStatus==='paid_externally').length} recorded paid. Showing ${visible.length}.`;
 $('#records').replaceChildren();
 for(const r of visible){const card=document.createElement('article');card.className='benefit sales-record';const heading=document.createElement('h2');heading.textContent=r.businessName||'Business not supplied';card.append(heading);const list=document.createElement('dl');const date=r.submittedAt?.toDate?.();const fields=[['Customer',r.customerName||'Not supplied'],['Reference',r.referralCode||r.id],['Plan discussed',label(r.planInterest)],['Submitted',date?date.toLocaleString():'Not recorded'],['Review',label(r.reviewStatus)],['Payment',label(r.paymentVerificationStatus)],['Commission',label(r.commissionStatus)]];if(admin)fields.push(['Agent',r.salesAgentName||'Not supplied']);if(Number.isInteger(r.commissionCents))fields.push(['Recorded commission',`${(r.commissionCents/100).toFixed(2)} ${r.commissionCurrency||r.currency||'(currency not recorded)'}`]);for(const [k,v]of fields){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;list.append(dt,dd);}card.append(list);$('#records').append(card);}
 if(!visible.length){const p=document.createElement('p');p.textContent=records.length?'No loaded records match these filters.':'No sales leads found for this account yet.';$('#records').append(p);}
}
function listen(user,version){stop?.();$('#sync').textContent='Connecting to shared sales records…';const constraints=admin?[limit(count)]:[where('salesAgentId','==',user.uid),limit(count)];stop=onSnapshot(query(collection(db,'sales_leads'),...constraints),{includeMetadataChanges:true},snapshot=>{if(version!==generation||auth.currentUser?.uid!==user.uid)return;records=snapshot.docs.map(d=>({...d.data(),id:d.id})).sort((a,b)=>(b.submittedAt?.toMillis?.()||0)-(a.submittedAt?.toMillis?.()||0));$('#more').hidden=snapshot.size<count;$('#sync').textContent=snapshot.metadata.fromCache?'Cached view: waiting for server confirmation.':`Connected · updated ${new Date().toLocaleTimeString()}`;render();},()=>{if(version!==generation)return;records=[];render();$('#more').hidden=true;$('#sync').textContent='Unable to read sales records. Check your connection and access, then reconnect.';});}
await connect(async user=>{const version=++generation;clear();count=50;admin=false;$('#title').textContent='My Sales';if(!user)return;if(!user.emailVerified){message('Verify your email before viewing sales.');return;}try{try{await getDocs(query(collection(db,'sales_invites'),limit(1)));admin=true;}catch{const staff=await getDoc(doc(db,'sales_staff',user.uid));if(!staff.exists()||staff.data().status!=='active')throw Error('inactive');}if(version!==generation||auth.currentUser?.uid!==user.uid)return;$('#dashboard').hidden=false;$('#title').textContent=admin?'Sales overview':'My Sales';message(admin?'Administrator access verified.':'Showing only records assigned to your account.');listen(user,version);}catch{if(version===generation)message('Sales access denied. Use an active sales account or your authorized owner account.');}});
$('#search').oninput=render;$('#filter').onchange=render;$('#more').onclick=()=>{count+=50;if(auth.currentUser)listen(auth.currentUser,generation);};$('#refresh').onclick=()=>{if(auth.currentUser)listen(auth.currentUser,generation);};window.addEventListener('pagehide',()=>stop?.());
