const guides={
  invite:{group:'For Eddy · owner',title:'Invite a new sales agent',summary:'Create an invitation from your phone or computer.',start:['Have the agent’s full name, exact email, mobile number, and territory ready.','Use your existing verified God account. A regular user or sales account cannot create invitations.'],steps:[
    ['Open your invitation desk','Open the Owner invitation desk and sign in with your authorized God email and password. Wait for “Owner access verified.”'],
    ['Enter the agent’s details','Under New sales agent, enter full name, exact sign-in email, phone with country code, and territory. Notes are optional and private. The invitation is tied to the email, not the nickname.'],
    ['Create the invitation','Tap Create invitation once and wait. This is your approval for this person to become an agent.'],
    ['Check the result','A QR, expiration date, and sharing buttons appear. The invitation lasts seven days and works once.'],
    ['Share before leaving','Use Share invitation + QR, Email link, Text link, Copy link, or Download QR. The private invitation link is available only in this page session. Save or send it before closing or refreshing.']
  ],done:'You see “Invitation created” and have sent or saved the private invitation.',notes:['An invitation does not activate the person immediately. They must verify the invited email and accept.','Sending a QR does not grant God access. It activates only the invited sales role after acceptance.'],action:['Open invitation desk','../owner/'],next:'share'},
  share:{group:'For Eddy · owner',title:'Send the invitation or QR',summary:'Choose email, text, another messaging app, or a saved image.',start:['Create the invitation first. Keep the invitation result visible.'],steps:[
    ['Share both the QR and message','Tap Share invitation + QR. On supported phones, choose your messaging app and the intended recipient. Review the message, then tap Send in that app.'],
    ['Send by email','Tap Email link. Your email app opens with the invited address and a prepared message. Review it and tap Send. This option sends the link; use the share sheet or attach the downloaded QR if you also want the image.'],
    ['Send by text','Tap Text link. Your messaging app should open with the phone number and message. Check the recipient, then send. If your device does not fill the message, use Copy link and paste it.'],
    ['Copy or download instead','Copy link lets you paste the invitation anywhere you choose. Download QR saves an image you can attach manually or show for the invited person to scan.'],
    ['Confirm with the agent','Ask them to open the invitation and use the exact email you entered. A delivery confirmation in your messaging app is separate from acceptance inside What’s Out.']
  ],done:'You have pressed Send in your messaging app, or handed the invited person the QR.',notes:['Creating an invitation does not automatically send email or SMS.','The private invitation QR is different from the agent’s customer-facing sales QR. Send this invitation only to the intended person.'],action:['Open invitation desk','../owner/'],next:'accept'},
  manage:{group:'For Eddy · owner',title:'Check, revoke, or replace invitations',summary:'Understand pending, claimed, expired, and revoked invitations.',start:['Sign in to the Owner invitation desk.'],steps:[
    ['View recent invitations','Scroll to Recent invitations and tap Refresh. The page shows the latest 25 records.'],
    ['Read the status','Pending means the invitation has not been accepted. Claimed means it was accepted. Expired means its seven-day window ended. Revoked means you canceled it.'],
    ['Cancel a pending invitation','Tap Revoke invitation on the correct record. Read the confirmation and confirm only if you want its link and QR to stop working.'],
    ['Replace a lost or incorrect invitation','Revoke the old pending invitation, then create another with the correct information. Send the new link; the old one will no longer work. Expired invitations may still need revocation before the backend allows a replacement for that email.'],
    ['Distinguish invitation from active access','Revocation applies to pending invitations. To suspend or remove an already active agent, use the existing God console in What’s Out; this web desk does not currently include active-agent management.']
  ],done:'The invitation list reflects the change after Refresh.',notes:['The backend stores a protected hash of the invitation secret. The web desk cannot recover an old private link from the list.','Revoking an invitation does not delete the person’s ordinary What’s Out account.'],action:['Open invitation desk','../owner/'],next:'invite'},
  accept:{group:'For invited agents',title:'Accept your invitation',summary:'Create or sign into your account and activate sales access on the web.',start:['Have the invitation link or QR from Eddy.','Use the exact email address he invited.'],steps:[
    ['Open the invitation','Tap the link or scan its QR. The invitation code fills automatically. Keep this tab open while completing email verification.'],
    ['Sign in or create your account','Already use What’s Out? Sign in. Otherwise open New to What’s Out? Create an account, choose a nickname, enter the invited email, and create a password.'],
    ['Verify your email','Open the verification message in your inbox and follow its link. Return to the invitation tab and tap I verified my email. If needed, use Send verification email and check spam.'],
    ['Check the account and code','The page shows the email you are signed in with. It must match the invitation. If the code is missing, reopen the original invitation link or paste the code Eddy provided.'],
    ['Accept','Tap Accept invitation and wait for the welcome message. Your sales access becomes active.'],
    ['Get your sales card','Tap Get my personal StepOut card. Sign in if asked, then open and bookmark your personal card.']
  ],done:'You see “Your sales access is active” and can open your personal StepOut card.',notes:['Acceptance does not buy a subscription.','An expired, revoked, already-used, or wrong-email invitation is rejected. Ask Eddy for help if necessary.'],action:['Open invitation acceptance','../join/'],next:'present'},
  present:{group:'For active agents',title:'Get and present your personal QR',summary:'Show the right card and preserve your sales attribution.',start:['You must already have accepted Eddy’s invitation and have active sales access.'],steps:[
    ['Get your personal link','Open Agent sign-in, use your verified sales account, and tap Open my personal StepOut card. Bookmark that personal link.'],
    ['Choose Business Owner','For a business subscription sale, choose Business Owner from your personal menu. Its QR carries your agent reference. A generic card opened from the main public homepage has no agent attribution.'],
    ['Introduce the benefit','Say: “I’m introducing What’s Out to local businesses. It helps people discover nearby places and gives owners tools for their business profile, events, and VIP invitations. May I show you a quick overview?”'],
    ['Let the owner scan','Show the large QR. The owner opens the business benefits page on their own phone. If scanning fails, use Copy QR link and send the link.'],
    ['Ask them to save the referral','Have the owner select Save my business referral, sign in, and wait for confirmation. A scan by itself does not save the connection.'],
    ['Explain the purchase step','The owner uses the same account when buying an eligible business subscription in the Android app. Google payment verification and Eddy’s review govern commission eligibility.']
  ],done:'The customer sees confirmation that their business referral was saved.',notes:['Free User and User+ cards do not carry commission attribution.','The invitation QR on Eddy’s desk recruits an agent. Your personal Business Owner QR is the one you show to customers.'],action:['Get my personal StepOut card','../agent/'],next:'customer'},
  customer:{group:'For business customers',title:'Save the agent who introduced you',summary:'Connect your account before buying a business subscription.',start:['Open the link or QR supplied by the agent.','Use the same What’s Out account you will use for the business purchase.'],steps:[
    ['Open the owner presentation','Scan the agent’s Business Owner QR and review the benefits.'],
    ['Select Save my business referral','This appears on a personal agent’s owner presentation. If it is missing, ask the agent for their personal QR instead of the generic public card.'],
    ['Sign in with a verified account','Enter your What’s Out email and password. If you do not have an account yet, use the Open What’s Out link on that page, register and verify your email, then return to save the referral.'],
    ['Wait for confirmation','Keep the page open until it confirms Referral saved and shows the agent. If a previous referral was already saved, the original agent stays attached.'],
    ['Continue your business setup','Register or claim your business and complete approval in What’s Out. When ready, buy the business subscription on Android using the same account.']
  ],done:'The page confirms the referral is saved to your account.',notes:['The website saves the referral; it does not process the subscription payment.','Scanning alone, using a different account, or closing before confirmation can prevent the intended connection.','The first saved agent remains attached. A referral already assigned to one business cannot be reused for another.'],action:['Open What’s Out','https://whatsout-fcc29.web.app/'],next:'credit'},
  credit:{group:'For Eddy and agents',title:'Understand sales credit and commission',summary:'Know what happens between a QR scan and an eligible commission.',start:['Only business subscriptions are included in this referral program.'],steps:[
    ['Invitation authorizes the agent','Eddy invites the agent. The agent verifies their email and accepts.'],
    ['The personal QR identifies the agent','The agent’s personal owner card carries an opaque reference. It does not grant the customer sales or administrator access.'],
    ['The customer saves the connection','Signing in and saving creates an unpaid lead linked to that customer account. This is attribution, not a completed sale.'],
    ['Google verifies the business purchase','The same customer account buys a qualifying business subscription through Google Play on Android. The backend checks the purchase and reads the saved referral.'],
    ['Eddy reviews the lead','A verified purchase still follows the existing administrator review. Only qualifying, reviewed records become eligible for commission.'],
    ['Payment is recorded separately','This feature does not automatically pay agents. The existing external commission-payment process remains separate.']
  ],done:'A qualified sale has a verified business purchase and the required review status.',notes:['User+ subscriptions, event passes, songs, and ads are excluded.','A restored purchase keeps its original attribution.','To inspect individual sales and commission status, use Sales Records & Commissions in the existing app; the web desk currently manages invitations only.'],action:['Open What’s Out','https://whatsout-fcc29.web.app/'],next:'trouble'},
  trouble:{group:'Help when stuck',title:'Troubleshoot a step',summary:'Common messages and the next action to take.',start:[],steps:[
    ['“Access denied” on the owner desk','Sign out and use your authorized, verified God account. Regular users and agents cannot invite people. Knowing the URL does not grant access.'],
    ['“Pending invitation already exists”','Find the existing invitation in Recent invitations. If its private link is lost or expired, revoke it and create a replacement.'],
    ['Wrong email, expired, or used invitation','Sign in with the exact invited email. If it expired or was revoked, ask Eddy for a new invitation. If already accepted, try Agent sign-in to obtain your card.'],
    ['Verification email is missing','Check spam and confirm the address. Tap Send verification email once, then wait. After following the email link, return and tap I verified my email.'],
    ['Nickname or profile setup failed','Choose a different available nickname. If the account was partly created, use Finish profile setup when offered; do not repeatedly create another account.'],
    ['Email/text/share button does not work','Use Copy link, paste it into your preferred messaging app, and send manually. Download QR provides a file you can attach. Device sharing features vary.'],
    ['Agent cannot generate a personal card','They must accept the invitation, verify their email, and remain active. Eddy can check their status in the existing God console.'],
    ['Customer referral was not saved','Reopen the agent’s personal owner link, select Save my business referral, and sign in with the verified purchase account. Wait for the confirmation.'],
    ['A purchase has no commission yet','A saved referral is not a payment. Check the same customer account, business subscription type, Google verification, and administrator review in Sales Records & Commissions.']
  ],done:'If the issue remains, record the exact message and the step where it appeared, then contact Eddy.',notes:['Never send passwords or private invitation codes in public posts.'],action:['Email Bitter Softworks','mailto:bittersoftworks@gmail.com'],next:'invite'}
};
const root=document.querySelector('#help');
const topic=new URLSearchParams(location.search).get('topic');
const guide=guides[topic];
if(!guide){
  document.title='How-to guides · StepOut';
  root.innerHTML=`<a class="back" href="../">← StepOut home</a><section class="benefit-hero"><div class="eyebrow">Keep this page bookmarked</div><h1>One step at a time.</h1><p class="lede">Choose the task you need help with. Each guide has numbered steps, the result to look for, and what to do next.</p></section><nav class="benefit-grid help-menu" aria-label="How-to topics">${Object.entries(guides).map(([key,g])=>`<a class="benefit" href="guide.html?topic=${key}"><span class="eyebrow">${g.group}</span><h2>${g.title}</h2><p>${g.summary}</p><strong>Read instructions →</strong></a>`).join('')}</nav>`;
}else{
  document.title=`${guide.title} · StepOut help`;
  root.innerHTML=`<a class="back" href="./">← All how-to guides</a><section class="benefit-hero"><div class="eyebrow">${guide.group}</div><h1>${guide.title}</h1><p class="lede">${guide.summary}</p><a class="button primary" href="${guide.action[1]}" target="_blank" rel="noopener">${guide.action[0]} ↗</a><p class="proofline">Opens in another tab so you can keep these instructions here.</p></section>${guide.start.length?`<aside class="notes"><h2>Before you start</h2><ul>${guide.start.map(text=>`<li>${text}</li>`).join('')}</ul></aside>`:''}<ol class="help-steps">${guide.steps.map(([title,text],i)=>`<li id="step-${i+1}" class="benefit"><span class="eyebrow">Step ${i+1}</span><h2>${title}</h2><p>${text}</p><a class="step-link" href="#step-${i+1}" aria-label="Link to step ${i+1}"># Step ${i+1}</a></li>`).join('')}</ol><section class="notes"><h2>How you know it worked</h2><p>${guide.done}</p>${guide.notes.length?`<ul>${guide.notes.map(text=>`<li>${text}</li>`).join('')}</ul>`:''}</section><nav class="card-tools"><a class="button" href="./">All guides</a><a class="button primary" href="guide.html?topic=${guide.next}">Next: ${guides[guide.next].title} →</a><button class="button" id="print">Print / save as PDF</button></nav>`;
  document.querySelector('#print').onclick=()=>window.print();
}
