const lessons=[
 {title:'1. Get ready—not just registered',body:`<p>Eddy invites agents by their exact email. Open your private invitation, sign in or create your account, verify that email, and accept. Invitations are single-use and expire after seven days.</p><p>Only an active, approved sales account can generate a personal card. An ordinary account, a training checkmark, or knowing the website address does not grant sales access.</p><p>Keep your invitation private. Invitation acceptance is not a signed agent agreement; confirm your agreement and compensation terms separately with Eddy.</p>`,guide:'accept'},
 {title:'2. Match a benefit to the business',body:`<p>Ask what the owner needs before showing features. What’s Out includes business registration or claiming, event-management workflows, and eligible VIP invitations and admission tools.</p><ul><li><strong>Restaurant with events:</strong> show the event workflow as a way to organize and share event information.</li><li><strong>Venue managing guests:</strong> explain eligible VIP invitations and QR admission, subject to authorized event access.</li><li><strong>Business needing discovery:</strong> explain registration or claiming. Approval is required before visibility.</li></ul><p>Publication depends on approval and an eligible business product, event pass, or supported credit. Show the current app before promising a feature. Discovery and loading depend on location, available data, network, device, and service conditions. Do not guarantee more sales, attendance, placement, or instant results.</p><p><a href="../benefits/business-owner/" target="_blank" rel="noopener">Read the business benefit presentation ↗</a></p>`,guide:'present'},
 {title:'3. Open a respectful conversation',body:`<p>Ask for the owner or manager and whether this is a good time. Keep the introduction short. If they are busy, ask when to return; if they decline, thank them and leave.</p><ul><li>“How do you currently promote your events?”</li><li>“What takes the most effort when organizing guests?”</li><li>“Would a quick overview be useful?”</li></ul><p>Listen, then show one relevant benefit. Do not say their online presence is missing unless you checked. Never promise a discount, free subscription, or earnings that Eddy has not authorized.</p>`,guide:'present'},
 {title:'4. Use the correct QR—and save the referral',body:`<ol><li>Sign into Agent access and open <strong>your personal StepOut card</strong>.</li><li>Select <strong>Business Owner</strong>. The generic homepage card is not attributed to you.</li><li>Let the owner scan on their own phone and review the benefits.</li><li>Ask them to choose <strong>Save my business referral</strong> and sign into their verified What’s Out account.</li><li>Wait for the saved-referral confirmation. Scanning alone is not enough.</li></ol><p>They must use the same account for an eligible Android business-subscription purchase. The first saved agent remains attached; do not try to replace another agent. Never ask for the customer’s password or sign in on their behalf.</p><p>The private invitation QR recruits an agent. Your personal Business Owner QR introduces customers. They are not interchangeable.</p>`,guide:'customer'},
 {title:'5. Explain payment and credit accurately',body:`<p>StepOut saves the referral; it does not sell or charge for the subscription. Show current products, prices, renewal terms, and availability in Google Play through What’s Out. Do not collect card details or cash through this presentation.</p><p>Sales attribution currently covers <strong>business subscriptions only</strong>. User+, event passes, songs, and ads are excluded.</p><p>A saved referral is an unpaid lead, not a completed sale. A qualifying purchase must be verified and reviewed by Eddy before commission eligibility. Commission payment is separate and is not automatic. A restored purchase keeps its original attribution.</p><p>Confirm current release readiness with Eddy: the complete real-customer purchase-to-commission path has not been demonstrated by the web training tests.</p>`,guide:'credit'},
 {title:'6. Handle questions and follow up',body:`<ul><li><strong>“We already use social media.”</strong> “That makes sense. I can show you the business and event tools so you can decide whether they add anything useful.”</li><li><strong>“Will it bring more customers?”</strong> “I can show the discovery tools, but I can’t guarantee visits or sales.”</li><li><strong>“How much?”</strong> “Let’s check the current plan and terms in the app together.”</li><li><strong>“I need time.”</strong> “Of course. Would you like the information link, and may I follow up?”</li></ul><p>Get permission before saving contact information or following up. Record only what is necessary in an approved place, not passwords or payment details. If something fails, note the exact message and ask Eddy—do not promise a workaround or mark a sale complete.</p><p>For security-verification errors, refresh the page, allow Google reCAPTCHA, and retry. For missing reset email, check spam. Never share your password or private invitation publicly.</p>`,guide:'trouble'}
];
const key='stepout-training-v1';let completed=[];let storageAvailable=true;
try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))completed=saved.filter(x=>Number.isInteger(x)&&x>=0&&x<lessons.length);}catch{storageAvailable=false;}
document.querySelector('#lessons').innerHTML=lessons.map((lesson,i)=>`<details class="benefit lesson" ${i===0?'open':''}><summary>${lesson.title}</summary>${lesson.body}<p><a href="../help/guide.html?topic=${lesson.guide}" target="_blank" rel="noopener">Open the related how-to ↗</a></p><label><input type="checkbox" data-lesson="${i}" ${completed.includes(i)?'checked':''}>I have read and understood this lesson</label></details>`).join('');
function update(){completed=[...document.querySelectorAll('[data-lesson]:checked')].map(x=>Number(x.dataset.lesson));try{localStorage.setItem(key,JSON.stringify(completed));}catch{storageAvailable=false;}document.querySelector('#progress').value=completed.length;document.querySelector('#progress-text').textContent=`${completed.length} of 6 lessons completed.${storageAvailable?'':' Progress cannot be saved in this browser.'}`;}
document.querySelectorAll('[data-lesson]').forEach(x=>x.addEventListener('change',update));update();
const questions=[
 ['Which QR do you show to a business prospect?',['My private invitation QR','My personal Business Owner QR','Any generic homepage QR'],1,'Use your personal Business Owner card so the link carries your agent reference.'],
 ['What saves the referral?',['A scan alone','The customer signs into a verified account and confirms saving','Reading the benefit page'],1,'Wait for the saved-referral confirmation; a scan alone is not attribution.'],
 ['Which purchase is included now?',['Every purchase','User+ membership','An eligible business subscription'],2,'Only business subscriptions are included.'],
 ['Can you guarantee more sales?',['Yes, once they subscribe','No—explain the tools and their limitations'],1,'Explain observable capabilities, not guaranteed business outcomes.'],
 ['When is a commission eligible?',['Immediately after scanning','After a qualifying verified purchase and required review'],1,'A lead is not a paid sale, and commission payment is separate.']
];
document.querySelector('#quiz').innerHTML=questions.map(([q,answers],i)=>`<fieldset><legend>${i+1}. ${q}</legend>${answers.map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}" required>${a}</label>`).join('')}<p class="feedback" id="feedback-${i}"></p></fieldset>`).join('')+'<button class="button primary" type="submit">Check my answers</button>';
document.querySelector('#quiz').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);let score=0;questions.forEach((q,i)=>{const correct=Number(data.get(`q${i}`))===q[2];if(correct)score++;document.querySelector(`#feedback-${i}`).textContent=(correct?'Correct. ':'Review this: ')+q[3];});document.querySelector('#quiz-result').textContent=`${score} of ${questions.length} correct. ${score===questions.length?'Practice check complete. Review the field checklist before your first visit.':'Review the explanations and try again.'} This does not activate or certify agent access.`;};
document.querySelector('#reset-progress').onclick=()=>{if(confirm('Clear lesson progress saved on this browser?')){document.querySelectorAll('[data-lesson]').forEach(x=>x.checked=false);update();}};
document.querySelector('#print').onclick=()=>{document.querySelectorAll('details').forEach(x=>x.open=true);window.print();};
