const {chromium}=require('playwright');const assert=require('node:assert/strict');
const sdk={
'firebase-app.js':'export const initializeApp=()=>({});',
'firebase-app-check.js':'export const initializeAppCheck=()=>({});export class ReCaptchaEnterpriseProvider {}',
'firebase-auth.js':`const a={currentUser:{uid:'agent1',emailVerified:true}};export const getAuth=()=>a;export const browserSessionPersistence={};export const setPersistence=async()=>{};export const signInWithEmailAndPassword=async()=>{};export const sendPasswordResetEmail=async()=>{};export const onAuthStateChanged=(_,cb)=>{window.authCB=cb;cb(a.currentUser)};export const signOut=async()=>{a.currentUser=null;await window.authCB(null)};`,
'firebase-functions.js':'export const getFunctions=()=>({});export const httpsCallable=()=>()=>{};',
'firebase-firestore.js':`export const getFirestore=()=>({});export const collection=(_,name)=>({name});export const doc=(_,name,id)=>({name,id});export const where=(field,op,value)=>({field,op,value});export const limit=n=>({limit:n});export const query=(c,...parts)=>({c,parts});export const getDocs=async()=>{if(!window.isAdmin)throw Error('denied');return {}};export const getDoc=async()=>({exists:()=>true,data:()=>({status:window.inactive?'suspended':'active'})});export const onSnapshot=(q,opts,cb)=>{window.lastQuery=q;window.updateSales=(status='not_verified')=>cb({docs:[{id:'one',data:()=>({businessName:'<img src=x onerror=alert(1)>',customerName:'Example',paymentVerificationStatus:status,commissionStatus:'not_eligible',salesAgentId:'agent1'})}],size:1,metadata:{fromCache:false}});window.updateSales();return ()=>{window.stopped=true}};`
};
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{async function open(flags={}){const p=await browser.newPage({viewport:{width:390,height:844}});await p.addInitScript(x=>Object.assign(window,x),flags);await p.route('https://www.gstatic.com/firebasejs/**',r=>r.fulfill({contentType:'application/javascript',body:sdk[new URL(r.request().url()).pathname.split('/').pop()]}));await p.goto('http://127.0.0.1:4173/sales/');return p;}const p=await open();await p.locator('#dashboard').waitFor();assert((await p.evaluate(()=>window.lastQuery.parts)).some(x=>x.field==='salesAgentId'&&x.value==='agent1'));assert.equal(await p.locator('#records img').count(),0);await p.evaluate(()=>window.updateSales('verified'));assert((await p.locator('#summary').textContent()).includes('1 verified purchases'));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('#logout').click();assert.equal(await p.locator('#dashboard').isVisible(),false);assert.equal(await p.locator('#records').textContent(),'');const denied=await open({inactive:true});await denied.getByText('Sales access denied.',{exact:false}).waitFor();assert.equal(await denied.locator('#dashboard').isVisible(),false);const admin=await open({isAdmin:true});await admin.locator('#dashboard').waitFor();assert.equal(await admin.locator('#title').textContent(),'Sales overview');console.log('PASS scoped agent query, suspended UI gate, administrator view, live update, safe text rendering, logout cleanup and mobile layout.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
